- babel.config.js
- jest.config.js
- package-lock.json
- package.json
- src/libs/ExtractData.js
- src/libs/ExtractData.test.js
also adds in Jest to do basic testing of this.
> Add ExtractData library

- package-lock.json
- package.json
- src/libs/ExtractData.js
- src/libs/ExtractData.test.js
- test/data/manifest.json
* Adds the axois-mock-adapter library
* handles manifests with thumbnails (iiif service and just jpg)
* changes the export from the ExtractData library
> Add an initial Manifest -> Thumbnail function.

- src/components/Search.vue
I should probably profile this.
> trying to improve search performance.

- src/components/Search.vue
adding pagination, handling the enter key; showing numbers
> adjusting input, adding pagination

- src/App.vue
- src/pages/Editor.vue
Was messing around and copy/pasting from RCV.  @szmoon, if you're farther along than this, please ignore!
> added some more UI bits

- src/libs/ACNLQRGenerator.js
The only real change here is in lines 159-167.  The rest is just prettier.
> recolored background

- package-lock.json
- package.json
- src/index.js
- src/pages/Editor.vue
plugging in Sentry and handling error that I saw in testing in Netlify
> add sentry

- config/webpack.config.js
- etc/paths.js
- package-lock.json
- package.json
- scripts/build.js
- src/index.js
- src/routers/index.js
hack to deploy it to a subdirectory and add google analytics
> wiring in webpack and google analytics

- src/pages/Editor.vue
changed the default, and set the title from the same place
> change default to spring

- .gitignore
- README.md
- package-lock.json
- package.json
added instructions and npm dependency to deploy to netlify
> Deploy setup

- src/assets/images/save-icon.svg
- src/components/ACNLQRGenerator.vue
- src/components/Gallery.vue
- src/components/ImageLoader.vue
- src/data/intro_text.md
- src/data/qr_instructions.md
- src/data/step3.md
- src/index.js
- src/libs/ACNLQRGenerator.js
- src/pages/Editor.vue
- src/style.scss
This is mostly for the steps 2 and 3 section, but has minor layout adjustments as well. Still need to figure out how to change the cropper size to be 100% width of the column - @workergnome have you come across a simple way to do this?
> Crop and preview

- package-lock.json
- package.json
- src/App.vue
fixing header and footer (partially)
> header_footer_update

- src/components/Search.vue
- src/libs/ExtractData.js
added updated data which included artist at 0 cost to the download file
> updated data

- src/components/ImageLoader.vue
- src/components/Search.vue
pushed this a few steps forward
> Search results and scroll

- package.json
- src/components/Gallery.vue
- src/components/Search.vue
- src/pages/Editor.vue
- worked with Kristen to improve scrolling behavior when a user selects something
- adding pagination information to the # of results section
- fixed display of 8/row and limited results to 16
> adjusting scrolls

- src/components/Gallery.vue
- src/components/Search.vue
- src/libs/ExtractData.js
- src/pages/Editor.vue
adjusting smooth scrolling, pagination, and search thumbnails
> Search results

- src/components/Gallery.vue
- src/components/ImageLoader.vue
- src/data/example_images.json
Adjusted the select from favorites gallery to be two rows of 6 on smaller screen sizes, and updated the example images. Accidentally saved linting on imageLoader (shouldn't be any changes there)
(still waiting on the name of one example image, so there's one double in there)
> Select from favorites

- src/libs/ExtractData.js
- src/libs/ExtractData.test.js
- src/pages/Editor.vue
- test/data/smithsonian_manifest.json
Still need to get title/logo and the like working, but this is a good first pass.
> External iiif now works.

- src/App.vue
- src/components/Gallery.vue
- src/components/ImageLoader.vue
- src/components/Search.vue
- src/data/example_images.json
- src/pages/Editor.vue
Haven't gotten to the iiif redo yet.. mostly styling changes so far
> Iiif and examples

- src/libs/ACNLQRGenerator.js
centers the title in the QR Code section
> center text in QR Code section

- src/components/UrlInput.vue
messed up. we use the prop eventBindings to feed all of the bindings in
> fixing event binding

- src/libs/ACNLQRGenerator.js
> left justify link in QR Code

- src/pages/Editor.vue
adds spacing between thirds when stacked
> adding spacing

- src/components/Search.vue
adds selected state for search
> add selected state for item

- src/components/Gallery.vue
- src/components/Search.vue
- src/data/example_images.json
- src/pages/Editor.vue
- Updated examples to be non-polarizing
- Made it so that 1st thumb was pre-selected (matching kristen's comps)
- Added in "unselecting" either the gallery or search thumbs if the user selects one from the other
> Update example artwork

- src/App.vue
- src/components/Share.vue
- src/pages/Editor.vue
- src/style.scss
Updated the styling for the share section so the images don't overflow the page boundary on mobile. Also updated the desktop spacing, and made the overall app's mobile and desktop gutters match getty-ui px
> update styling for share section, and main app gutters to match getty-ui

- src/components/Credits.vue
- src/components/IIIFInput.vue
- src/components/Search.vue
- src/components/Share.vue
- src/style.scss
Updates to handle: 
https://jira.getty.edu/browse/DEV-4691
https://jira.getty.edu/browse/DEV-4692
https://jira.getty.edu/browse/DEV-4694
https://jira.getty.edu/browse/DEV-4696
https://jira.getty.edu/browse/DEV-4697
https://jira.getty.edu/browse/DEV-4698
https://jira.getty.edu/browse/DEV-4699
> misc layout updates

- src/components/IIIFInput.vue
- src/pages/Editor.vue
1. the IIIF attribution can be html, making it render properly
2. when the IIIF Url is not valid we should show some user feedback -- fixing this.
this does not solve the case when the IIIF Url is valid, but there's a problem requesting the image
> Show iiif error message

- src/components/Search.vue
> hide pagination buttons

- src/components/Search.vue
updated containers holding search items to keep titles in bounds
added in a slight height limit to the search images for different screen sizes
> update search item styling

- src/App.vue
> maxwidth fix

- src/components/Search.vue
when you search for "" do nothing, but also reset the search
> disable empty search

- src/App.vue
this makes the Getty search button work.
obviously, super low priority
> add search overlay

- src/components/MetadataFields.vue
- src/pages/Editor.vue
* Fix layout of metadata for long key names
* Make license a link
* Don't show the collection link if it doesn't exist
* Add IIIF Content state so manifests can be shared.
(https://iiif.io/api/content-state/0.2/#initialization-mechanisms)
> Improvements to the IIIF handling.

- src/components/ImageLoader.vue
- src/pages/Editor.vue
I reviewed a bunch of our sentry errors and tried to pick some low hanging fruit to fix
> fix sentry exceptions

- src/components/ACNLQRGenerator.vue
- src/components/ImageLoader.vue
- src/libs/ACNLQRGenerator.js
- src/pages/Editor.vue
making all url requests handle security exceptions… better handling of timeout
> fixing bugs

- README.md
- package-lock.json
- package.json
update instructions and package
> update package and instructions

- src/components/Search.vue
pulls the datafile from our vpn instead of being bundled
> Use external datafile from VPN

- README.md
- config/webpack.config.js
- etc/env.js
- package.json
enables a production build for the AC Art generator to reduce the build size again
> cleanup build

- .circleci/config.yml
- .github/dependabot.yml
- package.json
adds circleci setup to publish to s3 bucket
> add circleci config

- .circleci/config.yml
- Dockerfile.nginx
- docker-compose.yml
attempts to publish a nginx endpoint to `ac-art-generator`
> add nginx host
